version: '3.8'
# Define the services that make up the application
services:
  # Define the dev-db service
  dev-db:
    # Use the postgres:15 image
    image: postgis/postgis:15-3.4
    # Map port 5432 in the container to port 5434 on the host
    ports:
      - 5434:5432
    # Set environment variables for the container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: p2p_dev
    # Connect the container to the imagineers network
    networks:
      - p2p-build
  # Define the test-db service
  test-db:
    # Use the postgres:15 image
    image: postgis/postgis:15-3.4
    # Map port 5432 in the container to port 5435 on the host
    ports:
      - 5435:5432
    # Set environment variables for the container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: p2p_test
    # Connect the container to the imagineers network
    networks:
      - p2p-build
# Define the network that the containers will use to communicate
networks:
  p2p-build: